# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BEJWCY_3apX37-Y0mbKhnnVcP-1kaSh5
"""

import streamlit as st
import base64

# Función para cargar la imagen en formato base64
def load_image(image_file):
    with open(image_file, "rb") as f:
        return base64.b64encode(f.read()).decode()

# Cargar la imagen
image_path = "valorant.jpg"  # Asegúrate de que la imagen esté en el mismo directorio
image_base64 = load_image(image_path)

# Configurar la página
st.set_page_config(page_title="Mi Aplicación", page_icon=":guardsman:", layout="wide")

# Cargar la imagen como fondo
st.markdown(
    f"""
    <style>
    .stApp {{
        background-image: url(data:image/jpeg;base64,{image_base64});
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
    }}
    </style>
    """,
    unsafe_allow_html=True
)

# Contenido de la aplicación
st.title("Bienvenido a mi aplicación")
st.write("Esta es una aplicación de ejemplo con una imagen de fondo.")